---
sidebar: sidebar 
permalink: concept_understand_activeiq_features.html 
keywords: activeiq, active iq digital advisor, features, upgrade, support offering 
summary: 提供有关信息板，监视列表，功能和小工具的信息。 
---
= 了解 Active IQ 的功能
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以使用 Active IQ 数字顾问在监视列表级别查看存储系统的整体状态，有关系统运行状况的详细信息，清单，规划，升级以及有价值的见解。

首次访问 Active IQ 数字顾问时，您可以创建监视列表，也可以搜索客户名称，站点名称，组名称， StorageGRID ，主机名， 集群，序列号或系统 ID 。

此外，您还应了解应用于卡的颜色，这些颜色表示风险的严重性和类型。

以下是 Active IQ 数字顾问的一些功能：

* 查看多个监视列表，以及可操作且有用的信息概览视图
* 深入了解存储系统面临的所有风险 以及降低风险的操作
* 使用 Active IQ Unified Manager 缓解风险
* 升级存储系统
* 查看运行 ONTAP 9.1 及更高版本的存储系统的存储效率比率，已用逻辑空间，已用物理空间以及节省的总数据
* 通过查看分析存储设备的性能 性能数据的图形格式
* 获取有关已过期的硬件和软件的信息 或即将在未来 6 个月内到期
* 使用 Ansible 更新 ONTAP 固件
* 获取有关容量超过 90% 或的系统的详细信息 容量接近 90%
* 查看详细的物理和逻辑配置信息，包括集群和节点配置摘要，本地层和卷信息，网络接口和端口信息，详细介绍磁盘和磁盘架信息的堆栈图以及一些缆线可视化功能
* 提供跨堆栈信息和见解，这些信息和见解有助于进行故障排除，升级评估，解决方案验证和迁移
* 检查主机的兼容性，并提供主机操作系统，驱动程序和固件的升级建议
* 准确了解您希望在中找到的内容 更智能，更快速



NOTE: 您可以从系统信息板上的 * 配置 * 小工具升级支持服务，以深入了解您的客户群并获得个性化支持。
