---
sidebar: sidebar 
permalink: digital-advisor-integration-with-bluexp.html 
keywords: digital advisor, integration, bluexp 
summary: 'Digital Advisor (以前称为Active IQ 数字顾问)现已与BlueXP完全集成。现在、您可以通过BlueXP用户界面(UI)管理集群并访问Digital Advisor的所有功能。' 
---
= Digital Advisor与BlueXP集成
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor (以前称为Active IQ 数字顾问)现已与BlueXP完全集成。现在、您可以通过BlueXP用户界面(UI)管理集群并访问Digital Advisor的所有功能。

借助BlueXP、IT专家和云架构师可以集中管理其混合多云基础架构。您只需一个NetApp 支持站点 (NSS)帐户即可访问BlueXP中的数字顾问。



== 集成概述

自2022年11月起、我们鼓励Digital Advisor用户在BlueXP中使用Digital Advisor。从BlueXP中、您可以访问与您习惯使用的相同的Digital Advisor界面、以及更多内容。借助BlueXP、您可以创建和管理云存储(例如Cloud Volumes ONTAP)、使用NetApp的数据服务(例如Cloud Backup)以及控制许多内部和边缘存储设备。



== 访问BlueXP中的Digital Advisor

您可以从BlueXP访问Digital Advisor来管理集群。

.步骤
. 打开 Web 浏览器并转到 https://cloudmanager.netapp.com/app-redirect/active-iq["BlueXP"^]
. 选择*使用您的NetApp 支持站点 凭据登录*并输入您的凭据。
+
如果您之前使用电子邮件和密码创建了BlueXP登录、则需要继续使用该登录选项。

. 出现提示时、使用NetApp 支持站点 凭据登录。
+
此登录与步骤2中完成的登录不同。在第2步中、您登录到了BlueXP平台。现在、您正在登录到Digital Advisor。



* 结果 *

此时将显示所有现有监视列表和配置、您现在可以像通常那样使用Digital Advisor。



== 了解有关BlueXP的更多信息

https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html["请访问BlueXP文档了解更多信息"^]
