---
sidebar: sidebar 
permalink: reference_limitations_activeiq.html 
keywords: limitation, issues, not supported, drawbacks 
summary: 提供有关此版本中限制的信息。 
---
= Digital Advisor的已知局限性
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。

存在以下限制：

* 仅适用于在 7- 模式下运行的 Data ONTAP 存储系统 （在 7- 模式下运行的 Data ONTAP 存储系统即将结束 支持生命周期）
+
** 性能图表
** 存储效率


* Upgrade Advisor 不支持 9.0 之前的集群模式 ONTAP 的升级计划。




== 编辑监视列表可能需要60分钟才能反映在Digital Advisor中

编辑监视列表不会立即更新Digital Advisor中的信息。这些更改可能需要长达60分钟才能在Digital Advisor中反映出来。



== 计划报告时，系统会显示一个空白报告

只有 SupportEdge Advisor 或 SupportEdge Expert 支持合同才提供计划的报告。如果您的系统不受 SupportEdge Advisor 或 SupportEdge Expert 支持合同的约束，则在计划报告时可能会收到空白报告。



== 已确认和未确认的风险可能需要60分钟才能反映在Digital Advisor中

已确认和未确认的风险状态不会立即反映在Digital Advisor中。这些变更可能需要长达60分钟才能反映在Digital Advisor和健康报告中。



== AutoSupport小工具不适用于集群和序列号

AutoSupport小工具不会为集群和序列号搜索提供警报。



== AutoSupport小工具无法深入查看串行级别AutoSupport详细信息

在AutoSupport报告页面上、单击任何状态、最近停止发送的系统或已关闭AutoSupport的系统不会导航到运行状况检查屏幕。



== "库存"小工具中不提供筛选和排序功能

您不能在清单小工具中筛选和排序数据。如果在"筛选依据"下拉列表中选择ONTAP AFF、ONTAP ASA、ONTAP Edge或ONTAP Select、则不会显示任何数据。
