---
sidebar: sidebar 
permalink: reference_new_activeiq.html 
keywords: 'what"s new, features, new' 
summary: 提供有关此版本中新增功能的信息。 
---
= Digital Advisor中的新增功能
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Digital Advisor引入了以下功能和增强功能：



== 2023年2月22日



=== 性能图表

您可以在卷IOPS图表中查看平均读取、写入和其他操作。



=== 存储效率

SAN和NAS存储效率可在节点级别提供给ONTAP 系统、包括AFF A系列、AFF C190、全SAN阵列和运行ONTAP 9.10及更高版本的FAS500。



== 2023年1月12日



=== 性能报告

您可以在卷级别的性能报告中查看平均读取、写入和其他操作。



== 2022年11月1日



=== Digital Advisor与BlueXP集成

Active IQ 数字顾问将改为Digital Advisor、现已集成到NetApp面向混合多云环境的统一管理控制台BlueXP中。 link:digital-advisor-integration-with-bluexp.html["了解更多信息。"]。



== 2022年8月25日



=== 清单

有关vCenter、ESXi主机和虚拟机的VMware资产信息现在包含在清单详细信息中、用于提供完整的堆栈清单和互操作性检查。 link:task-integrating-with-cloud-insights-to-view-vm-details.html["了解如何操作"]。



=== 多跃点升级

对于某些自动无中断升级(ANDU)到非相邻版本、您可以安装中间版本和目标版本的软件映像。自动升级过程使用后台的中间映像完成目标版本的更新。例如，如果集群运行的是 9.3 ，而您要升级到 9.7 ，则应加载 9.5 和 9.7 的 ONTAP 安装包，然后启动 andu 到 9.7 。然后， ONTAP 会先自动将集群升级到 9.5 ，然后再自动升级到 9.7 。在此过程中，您应该会执行多个接管 / 交还操作以及相关的重新启动。



== 2022年7月14日



=== 运行状况检查信息板

* 现在、您可以在运行状况检查信息板中查看为Cloud Volumes ONTAP 系统创建的技术案例详细信息。
* 添加了新的平台选项卡、可帮助您在不同平台的KPI之间轻松导航。




=== E系列系统

您可以使用建议的版本和运行状况检查KPI查看SANtricity 操作系统的版本。



=== 健康

引入了颜色编码、可快速轻松地识别不需要任何软件或固件版本升级的系统。



=== 升级工作流

现在、您可以查看E系列系统的升级建议。



== 2022年6月22日



=== StorageGRID

网格查看器中包含适用于StorageGRID 的信息生命周期管理(ILM)。



=== 云建议

为您提供了有关可使用SnapMirror数据复制移动到NetApp Cloud Volumes ONTAP 、NetApp Cloud Volumes Service 和NetApp Cloud Backup (以前称为AltaVault)的工作负载及其相应卷的建议。 link:task-informed-decisions-based-on-cloud-recommendations.html["了解如何操作"]。



=== 报告

* 现在、您可以使用为已生成的报告定义的条件生成报告。
* 现在、您可以尝试3次以重试生成失败的报告。
* 生成的报告的保留期限已从3天增加到90天。




== 2022年6月1日



=== 清单

* 现在、您可以查看"清单"中系统的销售代表信息。
* 现在、清单中提供了Astra控制中心系统。




== 2022年5月12日



=== StorageGRID

StorageGRID 容量和容量报告中包含其他容量指标。



=== 集群查看器

集群的SnapMirror (数据保护)摘要现在包含在ClusterViewer中。



=== 升级工作流

现在、您可以使用升级工作流查看目标E系列版本中提供的升级建议和新功能摘要。



=== 健康

* Ansible攻略手册已进行了改进、可降低软件配置风险。
* 这些筛选器已整合到健康操作和风险中。




== 2022 年 4 月 7 日



=== 健康

* 最新操作系统版本的关键建议评分以及支持合同和支持终止的 "6 个月 "KPI 评分已降低，以适应解决问题的紧迫性降低。
* 已更新有关远程管理和 HA 对（建议配置）的主要建议，以添加 NetApp 支持站点的 URL，以供客户自助服务使用。




== 2022 年 3 月 31 日



=== StorageGRID

您可以在网格查看器中查看有关租户和分段的信息。



== 2022 年 3 月 24 日



=== 运行状况检查信息板

* 运行状况评估的增强功能和错误修复内容摘要 PPT 。
* 能够生成建议的最低版本升级计划。
* 运行状况检查图块的增强功能，用于确定每个 KPI 需要关注的节点数。




=== StorageGRID

您可以在网格查看器中查看网格配置详细信息。



=== BlueXP

BlueXP用户现在可以在适用的情况下在新选项卡中打开Digital Advisor链接、类似于Digital Advisor中的现有功能。



== 2022 年 1 月 12 日



=== 配置变化

* 您可以克隆模板以创建原始模板的副本。
* 您可以与对这些模板具有只读或完全访问权限的其他授权用户共享黄金模板。link:task_manage_template.html["了解如何操作"]。




== 2021 年 12 月 15 日



=== 报告

* * 集群查看器报告 * ：此报告提供有关客户和监视列表级别的单个或多个集群的信息。您可以使用 ClusterViewer 报告将所有信息下载到一个文件中。您只能为最多包含 100 个节点的监视列表生成此报告。
* * 性能报告 * ：此报告在监视列表级别提供有关单个 zip 文件中集群，节点，本地层（聚合）和卷的性能信息。每个 zip 文件都包含一个集群的性能数据，可帮助用户分析每个集群的数据。您只能为最多包含 100 个节点的监视列表生成此报告。




=== 与 E 系列系统集成

您可以在Digital Advisor中查看选定E系列系统的容量详细信息和性能图。



== 2021 年 11 月 18 日



=== 存储效率

您可以查看由 NetApp Cloud Insights 维护和监控的节点的存储效率详细信息。



== 2021 年 11 月 11 日



=== 运行状况检查信息板

* 在这些运行状况检查图块上添加了图标，这些图标仅适用于具有 SupportEdge Advisor 和 SupportEdge Expert 支持服务的系统。已对 " 建议的软件 - 软件货币和固件货币 " 部分， " 建议的配置 " 和 " 最佳实践 " 进行了增强。
* 在Digital Advisor–Reports屏幕上为内部和外部(客户和合作伙伴)用户添加了一个机密数据横幅。




=== 健康和升级小工具

改进了信息板，在 " 健康行动历史记录 " 列中添加了 E 系列升级建议和风险触发日期。



=== 集群查看器

ClusterViewer 堆栈可视化模块已进行了增强，包括放大 / 缩小和保存映像功能。



=== 存储效率

您可以查看由 NetApp Cloud Insights 维护和监控的系统的存储效率详细信息。



== 2021 年 10 月 14 日



=== 可逆清单

现在，您可以在区域和站点级别生成 .yml 和 .ini 文件格式的 Ansible 清单文件。 link:task_view_inventory_details.html["了解如何操作"]。



=== 非活动数据报告（ IDR ）

在 FabricPool Advisor 屏幕中，您可以激活非活动数据报告（ IDR ）来监控聚合并生成可逆攻略手册。



=== 漂移时间线报告

您可以比较过去 90 天的 AutoSupport 数据并生成偏移时间线报告。 link:task_generate_drift_timeline_report.html["了解如何操作"]。



=== 合规系统切换

运行状况检查信息板已进行了增强，可通过切换来显示 " 最小操作系统 " 和 " 最新操作系统 " 选项卡，以便您可以查看合规且不符合建议和最新版本最低要求的系统。



=== 主要建议摘要

在运行状况检查信息板上，您可以查看前 5 个主要整体建议的摘要。



=== 适用于 NetApp Cloud Volumes ONTAP 和 E 系列平台的选项卡

运行状况检查信息板已通过 Cloud Volumes ONTAP * 和 E 系列选项卡进行了增强，因此您可以查看这些平台的运行状况检查 KPI 和详细信息。

此外，还为 ONTAP 添加了一个选项卡，并启用了其他平台。



=== Capacity

您可以在Digital Advisor中查看有关NetApp Cloud Volumes ONTAP 系统的容量详细信息。



=== 报告

报告时间表已延长至 12 个月。当计划报告即将过期时，您还会收到通知。



== 2021 年 9 月 30 日



=== 客户限定版本

客户认证版本可帮助支持客户经理（ SAM ）管理其客户部分安装群，其中托管的应用程序需要：

* 早期版本的 ONTAP ，有时不受支持
* 或经过测试和认证的客户安装群使用特定操作系统版本。




=== 技术案例工作流

在信息板和下拉屏幕中，数据图表和折线图都进行了图形增强。您也可以选择在条形图中查看该数据。在折线图窗口中，您可以在这两个用户界面中查看，选择和取消选择 " 已打开 " ， " 已关闭 " 和 " 案例总数 " 的图形。



=== 性能图形

现在，除了 CSV 格式之外，您还可以下载 PNG 和 JPG 格式的性能图。



=== 支持终止（ EOS ）控制器超过 12 个月

运行状况检查信息板已进行了改进，可通过一个选项卡显示 EOS 超过 12 个月的控制器。



== 2021 年 9 月 16 日



=== 健康

* 现在，勒索软件防护小工具属于健康工作流，而不是独立小工具。
* 在健康审查电子邮件中，您将找到有关勒索软件防护而非续订的信息。




=== Capacity

您可以在Digital Advisor中查看有关NetApp ONTAP®Select系统的容量详细信息。



=== 集群查看器

您可以在 ClusterViewer 的 "可视 化 " 选项卡中查看布线故障和其他错误。



== 2021 年 9 月 6 日



=== StorageGRID

* View AutoSupport ：查看 StorageGRID 和底层节点的 AutoSupport 日志。
* StorageGRID 设备详细信息：查看 StorageGRID 设备详细信息，例如节点类型，设备型号，驱动器大小，驱动器类型， RAID 模式， 等位于网格查看器 - 网格清单部分。
* 续订：查看要续订的网格和底层节点列表。
* E 系列 SANtricity 风险：在网格信息板 - 健康部分中查看底层节点的 E 系列 SANtricity 风险。




=== 容量预测

" 容量预测 " 小工具已更新，并改进了算法，可以更好地考虑系统重新配置。 link:reference_aiq_faq.html#capacity["了解更多信息。"]。



== 2021 年 8 月 26 日



=== Digital Advisor移动应用程序

现在、您可以在Digital Advisor移动应用程序上启用生物识别身份验证。根据您的移动电话支持的功能，可用于身份验证的选项会有所不同。

下载应用程序以了解更多信息：link:https://play.google.com/store/apps/details?id=com.netapp.myautosupport["Digital Advisor移动应用程序(Android)"^]
link:https://apps.apple.com/us/app/active-iq/id1230542480["Digital Advisor移动应用程序(iOS)"^]



=== 健康

健康小工具已通过勒索软件防护属性进行了增强。现在，您可以查看与勒索软件检测，预防和恢复相关的风险和更正操作。



== 2021 年 8 月 16 日



=== 健康审查

现在，您可以生成按需报告。此外，您还可以从 "Wellness Review 订阅 " 屏幕下载上次计划的报告。



=== 清单

现在，在网格清单选项卡中，您可以按站点级别以可扩展和可折叠的格式查看节点详细信息。



=== 混合型号集群标志

如果集群采用混合硬件型号，则应用于整个集群的操作系统版本是所有节点均可使用的版本。因此，较新硬件型号的某些节点的操作系统版本可能会从原来的位置降级。为了使这些混合模式集群更可见，我们应用了一个 " 混合模式 " 图标。



=== 建议的配置 / Storage Virtual Machine （ SVM ）运行状况：卷级别摘要

单击 SVM 表中的蓝色 ‘Volume Summary ' 框后，将显示一个弹出窗口，其中显示了有关托管或附加到特定序列号或物理节点的卷的详细信息。



== 2021 年 7 月 12 日



=== 系统固件

现在，您可以查看有关 ONTAP 主要版本和修补版本随附的系统固件的信息。您可以从 " 快速链接 " 菜单访问此功能。



=== 运行状况检查信息板

* 运行状况检查信息板已进行了改进，其中包含一个蓝色横幅，通知用户在计算运行状况得分时不会考虑 SupportEdge Advisor 和 SupportEdge Expert 不支持的系统。
* " 建议配置 " 小工具已进行了改进，可对 Storage VM （ SVM ）的失败检查进行深入分析，并可让您针对每个风险采取建议的更正操作。
* 现在，对于配置了不同硬件型号的集群中的所有节点，建议的目标 ONTAP 版本都相同。所有节点均支持此目标版本。
* 现在，您可以通过购买 PVR 来延长控制器，磁盘和磁盘架的 EOS 时间线。购买 PVR 后，您可以在支持结束小工具中查看 PVR 日期和扩展详细信息。PVR 详细信息也会在 EOSL 报告中提供。




=== 清单

您可以在详细清单页面上查看硬件，软件和不可退回磁盘的支持合同结束日期。



=== 支持服务升级

* 用户界面经过改进、可显示您在Digital Advisor中订阅的特定支持服务。
* 现在，您可以从系统信息板提出升级支持服务订阅的请求，以访问更多功能。 link:task_upgrade_support_offering.html["了解如何操作"]。




== 2021 年 6 月 25 日



=== Keystone订阅小工具

* 如果您选择让 ONTAP 收集器获取有关容量使用情况的数据，则可以在共享和磁盘选项卡中查看文件共享和磁盘的详细信息。您可以通过确定即将提交容量的存储空间来节省存储空间。
* 容量使用情况显示在 Keystone - 容量利用率信息板上，用于计费，现在基于逻辑容量。




== 2021 年 6 月 17 日



=== 报告

现在，您可以为 Storage VM 中任何一天，一周或一个月的所有卷生成聚合卷性能报告。



=== 健康状况审核电子邮件

改进了健康状况审核电子邮件，其中包含有关运行状况检查和升级操作中的支持和授权信息。



=== 升级工作流

* 用户界面已进行了增强，可为您提供信息的表视图。
* 现在，您可以在 " 升级详细信息 " 屏幕中查看有关 ONTAP 版本停止支持的信息。




=== 配置变化

* 配置驱动器现在支持 200 多个 AutoSupport 部分，用于创建黄金模板以及生成客户，站点，组，监视列表，集群， 和主机。
* 通过配置偏移，您可以使用配置偏移报告有效负载中包含的 Ansible 攻略手册来缓解偏差。




=== 运行状况检查信息板

此功能已得到增强，可将 Storage VM （ SVM ）与预定义的风险目录进行比较，以评估差距并建议相关的更正操作。



== 2021 年 6 月 9 日



=== 运行状况检查信息板

现在，您可以查看计算运行状况得分所依据的系统数量。此增强功能适用于运行状况检查信息板中的所有属性。



== 2021 年 5 月 20 日



=== 容量添加请求的 Drift 聊天

要获得有关容量添加请求的实时帮助，请直接从信息板与销售人员聊天。 link:task_identify_capacity_system.html["了解如何操作"]。



== 2021 年 4 月 29 日

* 下面介绍了如何保护您的系统免受黑客和勒索软件攻击。 link:task_increase_protection_against_hackers_and_Ransomware_attacks.html["了解如何操作"]。
* 您可以避免停机和可能的数据丢失。 link:task_avoid_the_downtime_and_possible_data_loss.html["了解如何操作"]。
* 了解如何避免卷填满以防止中断。 link:task_avoid_a_volume_filling_up_to_prevent_an_outage.html["了解如何操作"]。




== 2021 年 4 月 7 日



=== 监视列表

首次访问Digital Advisor时、您现在应创建监视列表、而不是信息板。您还可以查看不同监视列表的信息板，编辑现有监视列表的详细信息以及删除监视列表。



== 2021 年 2 月 24 日



=== 配置变化

此版本提供以下功能：

* 能够在创建模板期间编辑属性。
* 对 AutoSupport 部分进行分组。
* 在客户，站点，组，监视列表，集群， 和主机名。 link:task_compare_config_drift_template.html["了解如何操作"]。




=== 报告

您可以生成或计划容量和效率报告，以查看有关系统的容量和存储效率节省的详细信息。



== 2021 年 2 月 10 日



=== StorageGRID

StorageGRID 信息板可使用下一代 API 框架启用。

您可以使用 StorageGRID 信息板查看监视列表，客户，组和站点级别的信息。

此版本提供以下功能：

* * 清单小工具： * 查看选定级别下可用的 StorageGRID 系统的清单。
* * 健康小工具： * 查看所有风险和操作，包括与 StorageGRID 相关的风险和操作（如果这些风险和操作根据可用系统的现有 ARS 规则适用）。
* * 规划小工具： *
+
** * 容量增加： * 对于超过现有容量 70% 阈值的任何网格站点，您将收到通知。如果容量阈值可能超过 70% ，您可以选择在未来 1 ， 3 和 6 个月为站点中的 StorageGRID 添加容量。
** * 续订： * 对于许可证合同已过期或在未来 6 个月即将到期的任何 StorageGRID 系统，您将收到通知。您可以选择一个或多个系统向 NetApp 支持团队提出续订请求。


* * 网格信息板： * 网格信息板提供选定网格的运行状况，规划和配置详细信息。
* * 配置小工具： * 提供小工具中选定 StorageGRID 的基本详细信息，例如网格名称，主机名，序列号，型号，操作系统版本，客户名称，发货位置和联系详细信息。
* * 网格查看器： * 在 * 配置 * 小工具中，您可以单击 * 网格查看器 * 链接来详细查看网格配置。在 * 配置 * 小工具中，您可以单击 * 网格查看器 * 屏幕中的 * 下载 * 按钮来下载选定 StorageGRID 的站点详细信息和容量详细信息。
* * 站点详细信息： * 此选项卡提供了每个站点可用的网格摘要和存储节点。
* * 网格摘要： * 包含基本信息，例如许可证类型，许可证容量，已安装节点数，支持条款（终止许可证合同的日期），主管理节点和主管理节点的主站点。此选项卡还提供站点名称以及在相应站点下标记的存储节点数。在此版本中，您可以单击可用于查看相应站点存储节点的超链接来查看节点名称列表。
* * 容量详细信息选项卡： * 提供为网格配置的网格级别和站点容量详细信息。容量详细信息，例如 " 已安装存储容量 " ， " 可用存储容量 " ， " 已用总存储容量 " 以及 " 数据和元数据已用容量 " 。这些详细信息可在网格级别和站点级别查看。




=== FabricPool 顾问

"层数据"按钮已添加到FabricPool 信息板中、可用于使用NetApp BlueXP将数据分层到低成本对象存储层。



=== 云就绪工作负载

您可以查看存储系统中可用的不同类型的工作负载，并确定云就绪的工作负载。



== 2020 年 12 月 21 日



=== 运行状况检查信息板

信息板中添加了以下小工具：

* 推荐软件：此小工具提供了所有软件和固件升级以及货币建议的综合列表。
* 信号丢失：此小工具提供有关系统的分数和信息，这些系统由于某种原因已停止发送 AutoSupport 数据。它可提供有关在 7 天内是否未从主机名收到任何 AutoSupport 数据的信息。




== 2020 年 11 月 12 日



=== 使用 API 集成数据

您可以使用Digital Advisor API提取感兴趣的数据并将其直接集成到公司的工作流中。 link:concept_overview_API_service.html["了解更多信息。"]。



=== 健康—升级小工具

通过增强的 Risk Advisor 和 Upgrade Advisor 选项卡，您可以查看所有系统风险，并帮助您规划升级以降低所有风险。



=== 运行状况检查信息板

" 建议配置 " 小工具已添加到信息板中，它可提供有关远程管理风险，备用驱动器和故障驱动器风险以及 HA 对风险所监控的系统数量的摘要。



=== FabricPool 顾问

您可以通过监控集群来减少存储占用空间和相关成本，这些集群分为四类：非活动本地层（聚合）数据，非活动卷数据，分层数据以及未启用 IDR 的集群。



=== 以简体中文和日语进行本地化

Digital Advisor现在提供三种语言版本：中文、英文和日语。



=== 报告

您可以生成或计划 ClusterViewer 报告，以查看有关系统的物理和逻辑配置的详细信息。 link:task_generate_reports.html["了解如何操作"]。



== 2020 年 10 月 15 日



=== 运行状况检查信息板

通过Digital Advisor运行状况检查信息板、您可以对整个环境进行时间点审核。根据运行状况检查得分，您可以根据建议的 NetApp 最佳实践调整存储系统，以便于进行长期规划并改善客户群的运行状况。



=== 配置变化

通过此功能，您可以近乎实时地比较系统和集群配置以及检测配置差异。 link:task_add_config_drift_template.html["了解如何添加配置偏移模板"]。



=== AutoSupport

您可以查看 AutoSupport 数据并查看详细信息。



=== 健康审查订阅

您可以订阅接收每月电子邮件通知，其中汇总了系统的运行状况，这些系统即将续订日期，并且需要对客户群中的 NetApp 产品进行升级。 link:task_subscribe_to_wellness_review_email.html["立即订阅"]。



=== 报告

您可以使用报告功能立即生成报告，也可以计划每周或每月生成报告。 link:task_generate_reports.html["了解如何操作"]。



=== 手动 AutoSupport 上传

手动 AutoSupport 上传功能已得到增强，可改善用户体验。另外还提供了一列，用于添加有关上传状态的注释。



=== Keystone订阅小工具

您可以监控NetApp Keystone 订阅服务的已提交、已用和突发存储容量。



== 2020 年 9 月 30 日



=== 使用 Ansible 攻略手册的 AFF 和 FAS 固件

文档经过了改进，包括有关下载，安装和执行 AFF 和 FAS 固件 Ansible 自动化软件包的信息。

link:task_update_AFF_FAS_firmware.html["了解如何使用 Ansible 更新 AFF 和 FAS 固件 攻略手册"]。



== 2020 年 8 月 18 日



=== 性能

性能图已得到增强，可用于评估卷的性能。您可以在同一屏幕上的节点选项卡，集群选项卡，本地层选项卡和卷选项卡之间导航和切换。 link:task_view_performance_graphs.html["了解如何操作"]。



=== 使用 Ansible 攻略手册的 AFF 和 FAS 固件

AFF 和 FAS 固件屏幕已进行了增强，可提供更好的用户体验。



== 2020 年 7 月 17 日



=== 性能

性能图已得到增强，可用于评估本地层的性能。您可以在同一屏幕上的节点选项卡，集群选项卡和本地层选项卡之间导航和切换。



=== 健康

我们增强了健康属性，可以查看所有受影响的系统，而无需深入了解操作和风险。



== 2020 年 6 月 19 日



=== 生成清单报告

现在，您可以生成选定监视列表的报告，并将报告通过电子邮件发送给最多 5 个收件人。 link:task_view_inventory_details.html["了解如何操作"]。



=== 性能

性能图已得到增强，可用于评估存储系统的集群性能。您可以在同一屏幕上的节点选项卡和集群选项卡之间导航和切换。



=== 存储效率

存储效率小工具已进行了增强，可用于查看集群级别的存储效率比率和节省量。您可以在同一屏幕上的节点选项卡和集群选项卡之间导航和切换。



=== 更新默认主页

现在、您可以提供反馈、并告知我们您更新Digital Advisor默认主页屏幕的原因。



=== 更新到清单小工具

清单小工具经过改进，可提供用户友好的日期格式，额外的列用于平台支持结束和版本支持结束，从而改善用户体验。



== 2020 年 5 月 19 日



=== 设置默认主页

现在、您可以设置Digital Advisor的默认主页屏幕。您可以将其设置为Digital Advisor或Classic。



=== 存储效率

无论是否为AFF 系统、非AFF系统或这两者提供Snapshot副本、您都可以查看存储系统的存储效率比率和节省量。您可以在节点级别查看存储效率信息。 link:task_analyze_storage_efficiency.html["了解如何操作"]。



=== 性能

通过性能图，您可以评估存储设备在不同重要方面的性能。



=== 使用 Ansible 攻略手册升级 AFF 和 FAS 固件

在存储系统上使用 Ansible 更新 AFF 和 FAS 固件，以缓解已识别的风险并使存储系统保持最新。



=== 禁用健康评分功能

健康评分功能将暂时禁用，以改进评分算法并简化整体体验。



== 2020 年 4 月 2 日



=== 入门简介视频

入职视频可帮助用户快速熟悉Digital Advisor的选项和功能。



=== 健康评分

健康评分可根据高风险数量和已过期合同，为客户提供其客户群的综合分数。得分可以是 " 好 " ， " 平均 " 或 " 差 " 。



=== 风险摘要

风险摘要提供了有关风险，风险影响和更正操作的详细信息。



=== 支持确认和忽略风险

如果您希望缓解风险或无法缓解风险，可选择确认风险。



== 2020 年 3 月 19 日



=== 升级工作流

您可以使用升级工作流查看目标 ONTAP 版本中提供的升级建议和新功能摘要。 link:task_view_upgrade.html["了解如何操作"]。



=== 有价值的见解

您可以查看通过Digital Advisor获得的权益摘要以及您的支持合同。对于选定系统，价值报告整合了过去一年的优势。 link:task_view_valuable_insight_widget.html["立即查看"]。



=== 深入了解详细信息

提供更深入的信息，这是深入挖掘数据并根据需要立即深入了解聚合信息的构成的有力方式。



=== 增加容量

您可以主动识别已超过容量或容量接近 90% 的系统，并发送增加容量的请求。



== 2020 年 2 月 29 日



=== 增强的用户界面

最新的Digital Advisor信息板可提供个性化体验。它可以通过直观的方式在不同的信息板，小工具和屏幕上顺畅无缝地导航。它提供一体化体验。它可以传达比较结果，关系和趋势。它提供的洞察力有助于您根据不同信息板提供的数据检测和验证重要关系和有意义的差异。



=== 可自定义的信息板

通过在一个或多个页面或屏幕上提供有关数据的关键洞察和分析，帮助您一目了然地监控系统。您还可以创建多达 10 个信息板并做出有效的业务决策。

link:concept_overview_dashboard.html["了解更多信息。"]。



=== 使用 Active IQ Unified Manager 缓解风险

您可以使用 Active IQ Unified Manager 查看风险并进行更正。 link:task_view_risks_remediated_unified_manager.html["了解如何操作"]。



=== 健康

提供有关存储系统状态的详细信息，这些信息可分类为以下 6 个小工具：

* 性能和效率
* 可用性和保护
* Capacity
* Configuration
* 安全性
* 续订


请参见 link:concept_overview_wellness.html["分析健康属性"] 有关详细信息：



=== 更智能，更快速的搜索

用于使用单系统视图搜索参数，例如序列号，系统 ID ，主机名，站点名称，组名称和集群名称。您还可以搜索系统组，此外，您还可以按客户名称，站点名称或系统组名称进行搜索。
