---
sidebar: sidebar 
permalink: task-informed-decisions-based-on-cloud-recommendations.html 
keywords: cloud recommendations, migration, backup and archive, disaster recovery, FabricPool, FabricPool Advisor, inactive data, tiered data, IDR 
summary: 提供可根据其做出明智决策的建议。 
---
= 根据云建议做出明智的决策
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor会不断分析您的系统并提供建议、以提高系统性能、效率和运行状况。


NOTE: Digital Advisor会引导您进入NetApp Console 来实施建议。



== migration

提供有关存储系统中可用的不同工作负载类型的信息、并确定云就绪的工作负载。将工作负载迁移到云可节省成本并提供云灾难恢复。

建议将符合以下条件的卷迁移到Cloud Volumes ONTAP (CVO)：

* 卷应使用NFS、SMB、CIFS、FCP或iSCSI协议
* 不包括根卷
* 卷中的工作负载标记为Oracle、SAP、SAP HANA、MSSQL、MySQL、 SharePoint、文件共享、虚拟化和Trident
* 系统使用期限超过1年
* 支持合同将在6个月内结束


.步骤
. 从左窗格中、单击*云建议*。
. 单击*迁移*窗格中的任一链接。
. 单击“迁移到云”以启动“控制台”。




== 分层

提供有关非活动本地层(聚合)数据、非活动卷数据、分层数据和不受监控数据的信息。您可以通过监控冷数据或非活动数据并将其分层到低成本的对象存储层来减少存储占用空间和相关成本。


NOTE: 您可以启用非活动数据报告（ IDR ）以使用 Ansible 攻略手册文件生成 zip 文件。此信息可在客户，站点，组，监视列表，集群和节点级别获得。

建议对符合以下条件的卷进行分层：

* 卷应使用NFS、SMB或CIFS协议
* 不包括根卷
* 非活动数据超过50%
* 聚合容量超过50%


.步骤
. 从左窗格中、单击*云建议*。
. 单击*分层*窗格中的任一链接。
. 单击“*Tier Data*”以启动“*Console*”。


要了解有关 FabricPool 的更多信息，请参见 link:https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["FabricPool 最佳实践"^]。



== 备份和归档

提供有关应备份到云的系统的信息。您可以使用NetApp Cloud Backup保护系统安全、并在需要时将其还原。

建议将符合以下条件的卷备份到云：

* 不包括根卷
* 不包括具有SnapVault 备份的源卷、目标系统和卷。


.步骤
. 从左窗格中、单击*云建议*。
. 单击*备份和归档*窗格中的任一链接。
. 单击“备份到云”以启动“控制台”。




== Replication

提供有关应复制到云中的数据的信息、以便在发生灾难时提供帮助。

建议将符合以下条件的卷复制到云：

* 不包括根卷
* 不包括SnapMirror源卷
* 不包括SnapMirror目标卷(卷类型LS和DP)


.步骤
. 从左窗格中、单击*云建议*。
. 单击*灾难恢复*窗格中的任一链接。
. 单击“*复制到云*”以启动“控制台*”。

