---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: renew, hardware, software 
summary: 提供有关续订存储系统软件和硬件的信息。 
---
= 分析容量和存储效率节省情况
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以查看系统的容量详细信息和存储效率节省并采取适当措施。可以在集群级别或节点级别查看容量和存储效率信息。


NOTE: E 系列系统不支持此功能。

容量信息板可显示系统的容量详细信息和容量预测。容量预测使用历史容量信息来确定每个系统的利用率。根据已利用和已分配容量的历史数据（如果有一年的数据），该算法会考虑每个系统的当前利用率，并生成系统未来 1 到 6 个月的利用率预测。

存储效率信息板可显示运行ONTAP 9.1及更高版本的存储系统的数据精简率、已用逻辑空间、已用物理空间以及节省的总数据。对于AFF系统、非AF系统或这两者、使用和不使用Snapshot副本都可以看到数据精简率和节省量。每个效率功能(例如卷重复数据删除、卷压缩、数据缩减、FlexClone卷和Snapshot副本)均可显示客户存储中的总数据节省量。您可以查看效率比率最高的前5个存储系统。此外、您还可以在节点级别查看运行ONTAP 9.10及更高版本的ONTAP系统(包括AFF A系列、AFF C190、全SAN阵列和FAS500)的SAN和NAS效率、而无需Snapshot副本。

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.步骤
. 从左窗格中，单击 * 容量和效率 * 。
+
默认情况下，系统会选中 * 容量 * 选项卡。

. 查看集群和节点级别的容量详细信息。
+
.. 查看节点级别的容量预测。
+
对于 ONTAP 系统，可在 ClusterViewer 中查看有关原始容量的信息。

.. 单击 * 添加容量 * 向 NetApp 或您的合作伙伴发送添加容量的通知。


. 查看存储系统的存储效率和数据节省情况。
+
.. 如果存储系统的存储效率比率高于平均存储效率比率，请单击 * 分享您的成功案例 * ，让我们了解所遵循的最佳实践。
.. 如果存储系统的存储效率比率低于平均存储效率比率，请单击 * 联系我们 * ，告知我们您的存储系统配置。




有关容量和存储效率的详细信息，请参见 link:reference_aiq_faq.html["有关Digital Advisor的常见问题解答"]。
