---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: capacity, storage efficiency, data reduction, savings 
summary: 查看您的存储系统的容量详细信息和存储效率节省情况。 
---
= 在Digital Advisor中查看容量和存储效率节省情况
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以查看系统的容量详细信息和存储效率节省并采取适当措施。可以在集群级别或节点级别查看容量和存储效率信息。


NOTE: E 系列系统不支持此功能。

容量仪表板显示系统的容量详细信息和容量预测。容量预测使用历史容量信息来识别每个系统的利用率。基于已利用和分配容量的历史数据（一年的数据，如果可用），该算法考虑每个系统的当前利用率，并生成未来 1 至 6 个月系统利用率的预测。

存储效率仪表板显示数据缩减率、已用逻辑空间、已用物理空间以及节省的总数据量。对于 AFF 系统、非 AFF 系统或两者，无论有无快照副本，均可查看数据缩减率和节省量。可按效率功能（如卷重复数据删除、卷压缩、数据压缩、FlexClone 卷和快照副本）查看整个客户存储的总数据节省情况。您可以查看效率比率最高的前 5 个存储系统。您还可以在节点级别查看 ONTAP 系统（包括 AFF A-Series、AFF C190、All SAN Array 和 FAS500）在无快照副本情况下的 SAN 和 NAS 效率。

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.步骤
. 从左侧窗格中，选择*容量和效率*。
+
默认情况下，系统会选中 * 容量 * 选项卡。

. 查看集群和节点级别的容量详细信息。
+
.. 查看节点级别的容量预测。
+
对于 ONTAP 系统，可在 ClusterViewer 中查看有关原始容量的信息。



. 选择*添加容量*以向NetApp或您的合作伙伴发送通知以添加容量。
. 查看存储系统的存储效率和数据节省情况。
+
.. 如果存储系统的存储效率比率高于平均存储效率比率，请选择 *Share Your Success Story* 以告知我们遵循的最佳做法。
.. 如果您的存储系统的存储效率比率小于平均存储效率比率，请选择 *Contact Us* 以告知我们您的存储系统的配置。




有关容量和存储效率的详细信息，请参见 link:reference_aiq_faq.html["有关Digital Advisor的常见问题解答"]。
